// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

// Package mocks contains mock types for all interfaces.
//
// mocks are generated by mockery.
package mocks
