// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mocks

import (
	"go/types"
	"sync"

	"github.com/go-openapi/codescan/internal/ifaces"
	"github.com/go-openapi/spec"
)

// Ensure that MockSwaggerTypable does implement ifaces.SwaggerTypable.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.SwaggerTypable = &MockSwaggerTypable{}

// MockSwaggerTypable is a mock implementation of ifaces.SwaggerTypable.
//
//	func TestSomethingThatUsesSwaggerTypable(t *testing.T) {
//
//		// make and configure a mocked ifaces.SwaggerTypable
//		mockedSwaggerTypable := &MockSwaggerTypable{
//			AddExtensionFunc: func(key string, value any)  {
//				panic("mock out the AddExtension method")
//			},
//			InFunc: func() string {
//				panic("mock out the In method")
//			},
//			ItemsFunc: func() ifaces.SwaggerTypable {
//				panic("mock out the Items method")
//			},
//			LevelFunc: func() int {
//				panic("mock out the Level method")
//			},
//			SchemaFunc: func() *spec.Schema {
//				panic("mock out the Schema method")
//			},
//			SetRefFunc: func(ref spec.Ref)  {
//				panic("mock out the SetRef method")
//			},
//			TypedFunc: func(swaggerType string, format string)  {
//				panic("mock out the Typed method")
//			},
//			WithEnumFunc: func(values ...any)  {
//				panic("mock out the WithEnum method")
//			},
//			WithEnumDescriptionFunc: func(desc string)  {
//				panic("mock out the WithEnumDescription method")
//			},
//		}
//
//		// use mockedSwaggerTypable in code that requires ifaces.SwaggerTypable
//		// and then make assertions.
//
//	}
type MockSwaggerTypable struct {
	// AddExtensionFunc mocks the AddExtension method.
	AddExtensionFunc func(key string, value any)

	// InFunc mocks the In method.
	InFunc func() string

	// ItemsFunc mocks the Items method.
	ItemsFunc func() ifaces.SwaggerTypable

	// LevelFunc mocks the Level method.
	LevelFunc func() int

	// SchemaFunc mocks the Schema method.
	SchemaFunc func() *spec.Schema

	// SetRefFunc mocks the SetRef method.
	SetRefFunc func(ref spec.Ref)

	// TypedFunc mocks the Typed method.
	TypedFunc func(swaggerType string, format string)

	// WithEnumFunc mocks the WithEnum method.
	WithEnumFunc func(values ...any)

	// WithEnumDescriptionFunc mocks the WithEnumDescription method.
	WithEnumDescriptionFunc func(desc string)

	// calls tracks calls to the methods.
	calls struct {
		// AddExtension holds details about calls to the AddExtension method.
		AddExtension []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value any
		}
		// In holds details about calls to the In method.
		In []struct {
		}
		// Items holds details about calls to the Items method.
		Items []struct {
		}
		// Level holds details about calls to the Level method.
		Level []struct {
		}
		// Schema holds details about calls to the Schema method.
		Schema []struct {
		}
		// SetRef holds details about calls to the SetRef method.
		SetRef []struct {
			// Ref is the ref argument value.
			Ref spec.Ref
		}
		// Typed holds details about calls to the Typed method.
		Typed []struct {
			// SwaggerType is the swaggerType argument value.
			SwaggerType string
			// Format is the format argument value.
			Format string
		}
		// WithEnum holds details about calls to the WithEnum method.
		WithEnum []struct {
			// Values is the values argument value.
			Values []any
		}
		// WithEnumDescription holds details about calls to the WithEnumDescription method.
		WithEnumDescription []struct {
			// Desc is the desc argument value.
			Desc string
		}
	}
	lockAddExtension        sync.RWMutex
	lockIn                  sync.RWMutex
	lockItems               sync.RWMutex
	lockLevel               sync.RWMutex
	lockSchema              sync.RWMutex
	lockSetRef              sync.RWMutex
	lockTyped               sync.RWMutex
	lockWithEnum            sync.RWMutex
	lockWithEnumDescription sync.RWMutex
}

// AddExtension calls AddExtensionFunc.
func (mock *MockSwaggerTypable) AddExtension(key string, value any) {
	if mock.AddExtensionFunc == nil {
		panic("MockSwaggerTypable.AddExtensionFunc: method is nil but SwaggerTypable.AddExtension was just called")
	}
	callInfo := struct {
		Key   string
		Value any
	}{
		Key:   key,
		Value: value,
	}
	mock.lockAddExtension.Lock()
	mock.calls.AddExtension = append(mock.calls.AddExtension, callInfo)
	mock.lockAddExtension.Unlock()
	mock.AddExtensionFunc(key, value)
}

// AddExtensionCalls gets all the calls that were made to AddExtension.
// Check the length with:
//
//	len(mockedSwaggerTypable.AddExtensionCalls())
func (mock *MockSwaggerTypable) AddExtensionCalls() []struct {
	Key   string
	Value any
} {
	var calls []struct {
		Key   string
		Value any
	}
	mock.lockAddExtension.RLock()
	calls = mock.calls.AddExtension
	mock.lockAddExtension.RUnlock()
	return calls
}

// In calls InFunc.
func (mock *MockSwaggerTypable) In() string {
	if mock.InFunc == nil {
		panic("MockSwaggerTypable.InFunc: method is nil but SwaggerTypable.In was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIn.Lock()
	mock.calls.In = append(mock.calls.In, callInfo)
	mock.lockIn.Unlock()
	return mock.InFunc()
}

// InCalls gets all the calls that were made to In.
// Check the length with:
//
//	len(mockedSwaggerTypable.InCalls())
func (mock *MockSwaggerTypable) InCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIn.RLock()
	calls = mock.calls.In
	mock.lockIn.RUnlock()
	return calls
}

// Items calls ItemsFunc.
func (mock *MockSwaggerTypable) Items() ifaces.SwaggerTypable {
	if mock.ItemsFunc == nil {
		panic("MockSwaggerTypable.ItemsFunc: method is nil but SwaggerTypable.Items was just called")
	}
	callInfo := struct {
	}{}
	mock.lockItems.Lock()
	mock.calls.Items = append(mock.calls.Items, callInfo)
	mock.lockItems.Unlock()
	return mock.ItemsFunc()
}

// ItemsCalls gets all the calls that were made to Items.
// Check the length with:
//
//	len(mockedSwaggerTypable.ItemsCalls())
func (mock *MockSwaggerTypable) ItemsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockItems.RLock()
	calls = mock.calls.Items
	mock.lockItems.RUnlock()
	return calls
}

// Level calls LevelFunc.
func (mock *MockSwaggerTypable) Level() int {
	if mock.LevelFunc == nil {
		panic("MockSwaggerTypable.LevelFunc: method is nil but SwaggerTypable.Level was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLevel.Lock()
	mock.calls.Level = append(mock.calls.Level, callInfo)
	mock.lockLevel.Unlock()
	return mock.LevelFunc()
}

// LevelCalls gets all the calls that were made to Level.
// Check the length with:
//
//	len(mockedSwaggerTypable.LevelCalls())
func (mock *MockSwaggerTypable) LevelCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLevel.RLock()
	calls = mock.calls.Level
	mock.lockLevel.RUnlock()
	return calls
}

// Schema calls SchemaFunc.
func (mock *MockSwaggerTypable) Schema() *spec.Schema {
	if mock.SchemaFunc == nil {
		panic("MockSwaggerTypable.SchemaFunc: method is nil but SwaggerTypable.Schema was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSchema.Lock()
	mock.calls.Schema = append(mock.calls.Schema, callInfo)
	mock.lockSchema.Unlock()
	return mock.SchemaFunc()
}

// SchemaCalls gets all the calls that were made to Schema.
// Check the length with:
//
//	len(mockedSwaggerTypable.SchemaCalls())
func (mock *MockSwaggerTypable) SchemaCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSchema.RLock()
	calls = mock.calls.Schema
	mock.lockSchema.RUnlock()
	return calls
}

// SetRef calls SetRefFunc.
func (mock *MockSwaggerTypable) SetRef(ref spec.Ref) {
	if mock.SetRefFunc == nil {
		panic("MockSwaggerTypable.SetRefFunc: method is nil but SwaggerTypable.SetRef was just called")
	}
	callInfo := struct {
		Ref spec.Ref
	}{
		Ref: ref,
	}
	mock.lockSetRef.Lock()
	mock.calls.SetRef = append(mock.calls.SetRef, callInfo)
	mock.lockSetRef.Unlock()
	mock.SetRefFunc(ref)
}

// SetRefCalls gets all the calls that were made to SetRef.
// Check the length with:
//
//	len(mockedSwaggerTypable.SetRefCalls())
func (mock *MockSwaggerTypable) SetRefCalls() []struct {
	Ref spec.Ref
} {
	var calls []struct {
		Ref spec.Ref
	}
	mock.lockSetRef.RLock()
	calls = mock.calls.SetRef
	mock.lockSetRef.RUnlock()
	return calls
}

// Typed calls TypedFunc.
func (mock *MockSwaggerTypable) Typed(swaggerType string, format string) {
	if mock.TypedFunc == nil {
		panic("MockSwaggerTypable.TypedFunc: method is nil but SwaggerTypable.Typed was just called")
	}
	callInfo := struct {
		SwaggerType string
		Format      string
	}{
		SwaggerType: swaggerType,
		Format:      format,
	}
	mock.lockTyped.Lock()
	mock.calls.Typed = append(mock.calls.Typed, callInfo)
	mock.lockTyped.Unlock()
	mock.TypedFunc(swaggerType, format)
}

// TypedCalls gets all the calls that were made to Typed.
// Check the length with:
//
//	len(mockedSwaggerTypable.TypedCalls())
func (mock *MockSwaggerTypable) TypedCalls() []struct {
	SwaggerType string
	Format      string
} {
	var calls []struct {
		SwaggerType string
		Format      string
	}
	mock.lockTyped.RLock()
	calls = mock.calls.Typed
	mock.lockTyped.RUnlock()
	return calls
}

// WithEnum calls WithEnumFunc.
func (mock *MockSwaggerTypable) WithEnum(values ...any) {
	if mock.WithEnumFunc == nil {
		panic("MockSwaggerTypable.WithEnumFunc: method is nil but SwaggerTypable.WithEnum was just called")
	}
	callInfo := struct {
		Values []any
	}{
		Values: values,
	}
	mock.lockWithEnum.Lock()
	mock.calls.WithEnum = append(mock.calls.WithEnum, callInfo)
	mock.lockWithEnum.Unlock()
	mock.WithEnumFunc(values...)
}

// WithEnumCalls gets all the calls that were made to WithEnum.
// Check the length with:
//
//	len(mockedSwaggerTypable.WithEnumCalls())
func (mock *MockSwaggerTypable) WithEnumCalls() []struct {
	Values []any
} {
	var calls []struct {
		Values []any
	}
	mock.lockWithEnum.RLock()
	calls = mock.calls.WithEnum
	mock.lockWithEnum.RUnlock()
	return calls
}

// WithEnumDescription calls WithEnumDescriptionFunc.
func (mock *MockSwaggerTypable) WithEnumDescription(desc string) {
	if mock.WithEnumDescriptionFunc == nil {
		panic("MockSwaggerTypable.WithEnumDescriptionFunc: method is nil but SwaggerTypable.WithEnumDescription was just called")
	}
	callInfo := struct {
		Desc string
	}{
		Desc: desc,
	}
	mock.lockWithEnumDescription.Lock()
	mock.calls.WithEnumDescription = append(mock.calls.WithEnumDescription, callInfo)
	mock.lockWithEnumDescription.Unlock()
	mock.WithEnumDescriptionFunc(desc)
}

// WithEnumDescriptionCalls gets all the calls that were made to WithEnumDescription.
// Check the length with:
//
//	len(mockedSwaggerTypable.WithEnumDescriptionCalls())
func (mock *MockSwaggerTypable) WithEnumDescriptionCalls() []struct {
	Desc string
} {
	var calls []struct {
		Desc string
	}
	mock.lockWithEnumDescription.RLock()
	calls = mock.calls.WithEnumDescription
	mock.lockWithEnumDescription.RUnlock()
	return calls
}

// Ensure that MockValidationBuilder does implement ifaces.ValidationBuilder.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.ValidationBuilder = &MockValidationBuilder{}

// MockValidationBuilder is a mock implementation of ifaces.ValidationBuilder.
//
//	func TestSomethingThatUsesValidationBuilder(t *testing.T) {
//
//		// make and configure a mocked ifaces.ValidationBuilder
//		mockedValidationBuilder := &MockValidationBuilder{
//			SetDefaultFunc: func(defaultValue any)  {
//				panic("mock out the SetDefault method")
//			},
//			SetEnumFunc: func(enumValue string)  {
//				panic("mock out the SetEnum method")
//			},
//			SetExampleFunc: func(example any)  {
//				panic("mock out the SetExample method")
//			},
//			SetMaxItemsFunc: func(maxItems int64)  {
//				panic("mock out the SetMaxItems method")
//			},
//			SetMaxLengthFunc: func(maxLength int64)  {
//				panic("mock out the SetMaxLength method")
//			},
//			SetMaximumFunc: func(maxium float64, isExclusive bool)  {
//				panic("mock out the SetMaximum method")
//			},
//			SetMinItemsFunc: func(minItems int64)  {
//				panic("mock out the SetMinItems method")
//			},
//			SetMinLengthFunc: func(minLength int64)  {
//				panic("mock out the SetMinLength method")
//			},
//			SetMinimumFunc: func(minimum float64, isExclusive bool)  {
//				panic("mock out the SetMinimum method")
//			},
//			SetMultipleOfFunc: func(multiple float64)  {
//				panic("mock out the SetMultipleOf method")
//			},
//			SetPatternFunc: func(pattern string)  {
//				panic("mock out the SetPattern method")
//			},
//			SetUniqueFunc: func(isUniqueItems bool)  {
//				panic("mock out the SetUnique method")
//			},
//		}
//
//		// use mockedValidationBuilder in code that requires ifaces.ValidationBuilder
//		// and then make assertions.
//
//	}
type MockValidationBuilder struct {
	// SetDefaultFunc mocks the SetDefault method.
	SetDefaultFunc func(defaultValue any)

	// SetEnumFunc mocks the SetEnum method.
	SetEnumFunc func(enumValue string)

	// SetExampleFunc mocks the SetExample method.
	SetExampleFunc func(example any)

	// SetMaxItemsFunc mocks the SetMaxItems method.
	SetMaxItemsFunc func(maxItems int64)

	// SetMaxLengthFunc mocks the SetMaxLength method.
	SetMaxLengthFunc func(maxLength int64)

	// SetMaximumFunc mocks the SetMaximum method.
	SetMaximumFunc func(maxium float64, isExclusive bool)

	// SetMinItemsFunc mocks the SetMinItems method.
	SetMinItemsFunc func(minItems int64)

	// SetMinLengthFunc mocks the SetMinLength method.
	SetMinLengthFunc func(minLength int64)

	// SetMinimumFunc mocks the SetMinimum method.
	SetMinimumFunc func(minimum float64, isExclusive bool)

	// SetMultipleOfFunc mocks the SetMultipleOf method.
	SetMultipleOfFunc func(multiple float64)

	// SetPatternFunc mocks the SetPattern method.
	SetPatternFunc func(pattern string)

	// SetUniqueFunc mocks the SetUnique method.
	SetUniqueFunc func(isUniqueItems bool)

	// calls tracks calls to the methods.
	calls struct {
		// SetDefault holds details about calls to the SetDefault method.
		SetDefault []struct {
			// DefaultValue is the defaultValue argument value.
			DefaultValue any
		}
		// SetEnum holds details about calls to the SetEnum method.
		SetEnum []struct {
			// EnumValue is the enumValue argument value.
			EnumValue string
		}
		// SetExample holds details about calls to the SetExample method.
		SetExample []struct {
			// Example is the example argument value.
			Example any
		}
		// SetMaxItems holds details about calls to the SetMaxItems method.
		SetMaxItems []struct {
			// MaxItems is the maxItems argument value.
			MaxItems int64
		}
		// SetMaxLength holds details about calls to the SetMaxLength method.
		SetMaxLength []struct {
			// MaxLength is the maxLength argument value.
			MaxLength int64
		}
		// SetMaximum holds details about calls to the SetMaximum method.
		SetMaximum []struct {
			// Maxium is the maxium argument value.
			Maxium float64
			// IsExclusive is the isExclusive argument value.
			IsExclusive bool
		}
		// SetMinItems holds details about calls to the SetMinItems method.
		SetMinItems []struct {
			// MinItems is the minItems argument value.
			MinItems int64
		}
		// SetMinLength holds details about calls to the SetMinLength method.
		SetMinLength []struct {
			// MinLength is the minLength argument value.
			MinLength int64
		}
		// SetMinimum holds details about calls to the SetMinimum method.
		SetMinimum []struct {
			// Minimum is the minimum argument value.
			Minimum float64
			// IsExclusive is the isExclusive argument value.
			IsExclusive bool
		}
		// SetMultipleOf holds details about calls to the SetMultipleOf method.
		SetMultipleOf []struct {
			// Multiple is the multiple argument value.
			Multiple float64
		}
		// SetPattern holds details about calls to the SetPattern method.
		SetPattern []struct {
			// Pattern is the pattern argument value.
			Pattern string
		}
		// SetUnique holds details about calls to the SetUnique method.
		SetUnique []struct {
			// IsUniqueItems is the isUniqueItems argument value.
			IsUniqueItems bool
		}
	}
	lockSetDefault    sync.RWMutex
	lockSetEnum       sync.RWMutex
	lockSetExample    sync.RWMutex
	lockSetMaxItems   sync.RWMutex
	lockSetMaxLength  sync.RWMutex
	lockSetMaximum    sync.RWMutex
	lockSetMinItems   sync.RWMutex
	lockSetMinLength  sync.RWMutex
	lockSetMinimum    sync.RWMutex
	lockSetMultipleOf sync.RWMutex
	lockSetPattern    sync.RWMutex
	lockSetUnique     sync.RWMutex
}

// SetDefault calls SetDefaultFunc.
func (mock *MockValidationBuilder) SetDefault(defaultValue any) {
	if mock.SetDefaultFunc == nil {
		panic("MockValidationBuilder.SetDefaultFunc: method is nil but ValidationBuilder.SetDefault was just called")
	}
	callInfo := struct {
		DefaultValue any
	}{
		DefaultValue: defaultValue,
	}
	mock.lockSetDefault.Lock()
	mock.calls.SetDefault = append(mock.calls.SetDefault, callInfo)
	mock.lockSetDefault.Unlock()
	mock.SetDefaultFunc(defaultValue)
}

// SetDefaultCalls gets all the calls that were made to SetDefault.
// Check the length with:
//
//	len(mockedValidationBuilder.SetDefaultCalls())
func (mock *MockValidationBuilder) SetDefaultCalls() []struct {
	DefaultValue any
} {
	var calls []struct {
		DefaultValue any
	}
	mock.lockSetDefault.RLock()
	calls = mock.calls.SetDefault
	mock.lockSetDefault.RUnlock()
	return calls
}

// SetEnum calls SetEnumFunc.
func (mock *MockValidationBuilder) SetEnum(enumValue string) {
	if mock.SetEnumFunc == nil {
		panic("MockValidationBuilder.SetEnumFunc: method is nil but ValidationBuilder.SetEnum was just called")
	}
	callInfo := struct {
		EnumValue string
	}{
		EnumValue: enumValue,
	}
	mock.lockSetEnum.Lock()
	mock.calls.SetEnum = append(mock.calls.SetEnum, callInfo)
	mock.lockSetEnum.Unlock()
	mock.SetEnumFunc(enumValue)
}

// SetEnumCalls gets all the calls that were made to SetEnum.
// Check the length with:
//
//	len(mockedValidationBuilder.SetEnumCalls())
func (mock *MockValidationBuilder) SetEnumCalls() []struct {
	EnumValue string
} {
	var calls []struct {
		EnumValue string
	}
	mock.lockSetEnum.RLock()
	calls = mock.calls.SetEnum
	mock.lockSetEnum.RUnlock()
	return calls
}

// SetExample calls SetExampleFunc.
func (mock *MockValidationBuilder) SetExample(example any) {
	if mock.SetExampleFunc == nil {
		panic("MockValidationBuilder.SetExampleFunc: method is nil but ValidationBuilder.SetExample was just called")
	}
	callInfo := struct {
		Example any
	}{
		Example: example,
	}
	mock.lockSetExample.Lock()
	mock.calls.SetExample = append(mock.calls.SetExample, callInfo)
	mock.lockSetExample.Unlock()
	mock.SetExampleFunc(example)
}

// SetExampleCalls gets all the calls that were made to SetExample.
// Check the length with:
//
//	len(mockedValidationBuilder.SetExampleCalls())
func (mock *MockValidationBuilder) SetExampleCalls() []struct {
	Example any
} {
	var calls []struct {
		Example any
	}
	mock.lockSetExample.RLock()
	calls = mock.calls.SetExample
	mock.lockSetExample.RUnlock()
	return calls
}

// SetMaxItems calls SetMaxItemsFunc.
func (mock *MockValidationBuilder) SetMaxItems(maxItems int64) {
	if mock.SetMaxItemsFunc == nil {
		panic("MockValidationBuilder.SetMaxItemsFunc: method is nil but ValidationBuilder.SetMaxItems was just called")
	}
	callInfo := struct {
		MaxItems int64
	}{
		MaxItems: maxItems,
	}
	mock.lockSetMaxItems.Lock()
	mock.calls.SetMaxItems = append(mock.calls.SetMaxItems, callInfo)
	mock.lockSetMaxItems.Unlock()
	mock.SetMaxItemsFunc(maxItems)
}

// SetMaxItemsCalls gets all the calls that were made to SetMaxItems.
// Check the length with:
//
//	len(mockedValidationBuilder.SetMaxItemsCalls())
func (mock *MockValidationBuilder) SetMaxItemsCalls() []struct {
	MaxItems int64
} {
	var calls []struct {
		MaxItems int64
	}
	mock.lockSetMaxItems.RLock()
	calls = mock.calls.SetMaxItems
	mock.lockSetMaxItems.RUnlock()
	return calls
}

// SetMaxLength calls SetMaxLengthFunc.
func (mock *MockValidationBuilder) SetMaxLength(maxLength int64) {
	if mock.SetMaxLengthFunc == nil {
		panic("MockValidationBuilder.SetMaxLengthFunc: method is nil but ValidationBuilder.SetMaxLength was just called")
	}
	callInfo := struct {
		MaxLength int64
	}{
		MaxLength: maxLength,
	}
	mock.lockSetMaxLength.Lock()
	mock.calls.SetMaxLength = append(mock.calls.SetMaxLength, callInfo)
	mock.lockSetMaxLength.Unlock()
	mock.SetMaxLengthFunc(maxLength)
}

// SetMaxLengthCalls gets all the calls that were made to SetMaxLength.
// Check the length with:
//
//	len(mockedValidationBuilder.SetMaxLengthCalls())
func (mock *MockValidationBuilder) SetMaxLengthCalls() []struct {
	MaxLength int64
} {
	var calls []struct {
		MaxLength int64
	}
	mock.lockSetMaxLength.RLock()
	calls = mock.calls.SetMaxLength
	mock.lockSetMaxLength.RUnlock()
	return calls
}

// SetMaximum calls SetMaximumFunc.
func (mock *MockValidationBuilder) SetMaximum(maxium float64, isExclusive bool) {
	if mock.SetMaximumFunc == nil {
		panic("MockValidationBuilder.SetMaximumFunc: method is nil but ValidationBuilder.SetMaximum was just called")
	}
	callInfo := struct {
		Maxium      float64
		IsExclusive bool
	}{
		Maxium:      maxium,
		IsExclusive: isExclusive,
	}
	mock.lockSetMaximum.Lock()
	mock.calls.SetMaximum = append(mock.calls.SetMaximum, callInfo)
	mock.lockSetMaximum.Unlock()
	mock.SetMaximumFunc(maxium, isExclusive)
}

// SetMaximumCalls gets all the calls that were made to SetMaximum.
// Check the length with:
//
//	len(mockedValidationBuilder.SetMaximumCalls())
func (mock *MockValidationBuilder) SetMaximumCalls() []struct {
	Maxium      float64
	IsExclusive bool
} {
	var calls []struct {
		Maxium      float64
		IsExclusive bool
	}
	mock.lockSetMaximum.RLock()
	calls = mock.calls.SetMaximum
	mock.lockSetMaximum.RUnlock()
	return calls
}

// SetMinItems calls SetMinItemsFunc.
func (mock *MockValidationBuilder) SetMinItems(minItems int64) {
	if mock.SetMinItemsFunc == nil {
		panic("MockValidationBuilder.SetMinItemsFunc: method is nil but ValidationBuilder.SetMinItems was just called")
	}
	callInfo := struct {
		MinItems int64
	}{
		MinItems: minItems,
	}
	mock.lockSetMinItems.Lock()
	mock.calls.SetMinItems = append(mock.calls.SetMinItems, callInfo)
	mock.lockSetMinItems.Unlock()
	mock.SetMinItemsFunc(minItems)
}

// SetMinItemsCalls gets all the calls that were made to SetMinItems.
// Check the length with:
//
//	len(mockedValidationBuilder.SetMinItemsCalls())
func (mock *MockValidationBuilder) SetMinItemsCalls() []struct {
	MinItems int64
} {
	var calls []struct {
		MinItems int64
	}
	mock.lockSetMinItems.RLock()
	calls = mock.calls.SetMinItems
	mock.lockSetMinItems.RUnlock()
	return calls
}

// SetMinLength calls SetMinLengthFunc.
func (mock *MockValidationBuilder) SetMinLength(minLength int64) {
	if mock.SetMinLengthFunc == nil {
		panic("MockValidationBuilder.SetMinLengthFunc: method is nil but ValidationBuilder.SetMinLength was just called")
	}
	callInfo := struct {
		MinLength int64
	}{
		MinLength: minLength,
	}
	mock.lockSetMinLength.Lock()
	mock.calls.SetMinLength = append(mock.calls.SetMinLength, callInfo)
	mock.lockSetMinLength.Unlock()
	mock.SetMinLengthFunc(minLength)
}

// SetMinLengthCalls gets all the calls that were made to SetMinLength.
// Check the length with:
//
//	len(mockedValidationBuilder.SetMinLengthCalls())
func (mock *MockValidationBuilder) SetMinLengthCalls() []struct {
	MinLength int64
} {
	var calls []struct {
		MinLength int64
	}
	mock.lockSetMinLength.RLock()
	calls = mock.calls.SetMinLength
	mock.lockSetMinLength.RUnlock()
	return calls
}

// SetMinimum calls SetMinimumFunc.
func (mock *MockValidationBuilder) SetMinimum(minimum float64, isExclusive bool) {
	if mock.SetMinimumFunc == nil {
		panic("MockValidationBuilder.SetMinimumFunc: method is nil but ValidationBuilder.SetMinimum was just called")
	}
	callInfo := struct {
		Minimum     float64
		IsExclusive bool
	}{
		Minimum:     minimum,
		IsExclusive: isExclusive,
	}
	mock.lockSetMinimum.Lock()
	mock.calls.SetMinimum = append(mock.calls.SetMinimum, callInfo)
	mock.lockSetMinimum.Unlock()
	mock.SetMinimumFunc(minimum, isExclusive)
}

// SetMinimumCalls gets all the calls that were made to SetMinimum.
// Check the length with:
//
//	len(mockedValidationBuilder.SetMinimumCalls())
func (mock *MockValidationBuilder) SetMinimumCalls() []struct {
	Minimum     float64
	IsExclusive bool
} {
	var calls []struct {
		Minimum     float64
		IsExclusive bool
	}
	mock.lockSetMinimum.RLock()
	calls = mock.calls.SetMinimum
	mock.lockSetMinimum.RUnlock()
	return calls
}

// SetMultipleOf calls SetMultipleOfFunc.
func (mock *MockValidationBuilder) SetMultipleOf(multiple float64) {
	if mock.SetMultipleOfFunc == nil {
		panic("MockValidationBuilder.SetMultipleOfFunc: method is nil but ValidationBuilder.SetMultipleOf was just called")
	}
	callInfo := struct {
		Multiple float64
	}{
		Multiple: multiple,
	}
	mock.lockSetMultipleOf.Lock()
	mock.calls.SetMultipleOf = append(mock.calls.SetMultipleOf, callInfo)
	mock.lockSetMultipleOf.Unlock()
	mock.SetMultipleOfFunc(multiple)
}

// SetMultipleOfCalls gets all the calls that were made to SetMultipleOf.
// Check the length with:
//
//	len(mockedValidationBuilder.SetMultipleOfCalls())
func (mock *MockValidationBuilder) SetMultipleOfCalls() []struct {
	Multiple float64
} {
	var calls []struct {
		Multiple float64
	}
	mock.lockSetMultipleOf.RLock()
	calls = mock.calls.SetMultipleOf
	mock.lockSetMultipleOf.RUnlock()
	return calls
}

// SetPattern calls SetPatternFunc.
func (mock *MockValidationBuilder) SetPattern(pattern string) {
	if mock.SetPatternFunc == nil {
		panic("MockValidationBuilder.SetPatternFunc: method is nil but ValidationBuilder.SetPattern was just called")
	}
	callInfo := struct {
		Pattern string
	}{
		Pattern: pattern,
	}
	mock.lockSetPattern.Lock()
	mock.calls.SetPattern = append(mock.calls.SetPattern, callInfo)
	mock.lockSetPattern.Unlock()
	mock.SetPatternFunc(pattern)
}

// SetPatternCalls gets all the calls that were made to SetPattern.
// Check the length with:
//
//	len(mockedValidationBuilder.SetPatternCalls())
func (mock *MockValidationBuilder) SetPatternCalls() []struct {
	Pattern string
} {
	var calls []struct {
		Pattern string
	}
	mock.lockSetPattern.RLock()
	calls = mock.calls.SetPattern
	mock.lockSetPattern.RUnlock()
	return calls
}

// SetUnique calls SetUniqueFunc.
func (mock *MockValidationBuilder) SetUnique(isUniqueItems bool) {
	if mock.SetUniqueFunc == nil {
		panic("MockValidationBuilder.SetUniqueFunc: method is nil but ValidationBuilder.SetUnique was just called")
	}
	callInfo := struct {
		IsUniqueItems bool
	}{
		IsUniqueItems: isUniqueItems,
	}
	mock.lockSetUnique.Lock()
	mock.calls.SetUnique = append(mock.calls.SetUnique, callInfo)
	mock.lockSetUnique.Unlock()
	mock.SetUniqueFunc(isUniqueItems)
}

// SetUniqueCalls gets all the calls that were made to SetUnique.
// Check the length with:
//
//	len(mockedValidationBuilder.SetUniqueCalls())
func (mock *MockValidationBuilder) SetUniqueCalls() []struct {
	IsUniqueItems bool
} {
	var calls []struct {
		IsUniqueItems bool
	}
	mock.lockSetUnique.RLock()
	calls = mock.calls.SetUnique
	mock.lockSetUnique.RUnlock()
	return calls
}

// Ensure that MockValueParser does implement ifaces.ValueParser.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.ValueParser = &MockValueParser{}

// MockValueParser is a mock implementation of ifaces.ValueParser.
//
//	func TestSomethingThatUsesValueParser(t *testing.T) {
//
//		// make and configure a mocked ifaces.ValueParser
//		mockedValueParser := &MockValueParser{
//			MatchesFunc: func(commentLine string) bool {
//				panic("mock out the Matches method")
//			},
//			ParseFunc: func(commentlines []string) error {
//				panic("mock out the Parse method")
//			},
//		}
//
//		// use mockedValueParser in code that requires ifaces.ValueParser
//		// and then make assertions.
//
//	}
type MockValueParser struct {
	// MatchesFunc mocks the Matches method.
	MatchesFunc func(commentLine string) bool

	// ParseFunc mocks the Parse method.
	ParseFunc func(commentlines []string) error

	// calls tracks calls to the methods.
	calls struct {
		// Matches holds details about calls to the Matches method.
		Matches []struct {
			// CommentLine is the commentLine argument value.
			CommentLine string
		}
		// Parse holds details about calls to the Parse method.
		Parse []struct {
			// Commentlines is the commentlines argument value.
			Commentlines []string
		}
	}
	lockMatches sync.RWMutex
	lockParse   sync.RWMutex
}

// Matches calls MatchesFunc.
func (mock *MockValueParser) Matches(commentLine string) bool {
	if mock.MatchesFunc == nil {
		panic("MockValueParser.MatchesFunc: method is nil but ValueParser.Matches was just called")
	}
	callInfo := struct {
		CommentLine string
	}{
		CommentLine: commentLine,
	}
	mock.lockMatches.Lock()
	mock.calls.Matches = append(mock.calls.Matches, callInfo)
	mock.lockMatches.Unlock()
	return mock.MatchesFunc(commentLine)
}

// MatchesCalls gets all the calls that were made to Matches.
// Check the length with:
//
//	len(mockedValueParser.MatchesCalls())
func (mock *MockValueParser) MatchesCalls() []struct {
	CommentLine string
} {
	var calls []struct {
		CommentLine string
	}
	mock.lockMatches.RLock()
	calls = mock.calls.Matches
	mock.lockMatches.RUnlock()
	return calls
}

// Parse calls ParseFunc.
func (mock *MockValueParser) Parse(commentlines []string) error {
	if mock.ParseFunc == nil {
		panic("MockValueParser.ParseFunc: method is nil but ValueParser.Parse was just called")
	}
	callInfo := struct {
		Commentlines []string
	}{
		Commentlines: commentlines,
	}
	mock.lockParse.Lock()
	mock.calls.Parse = append(mock.calls.Parse, callInfo)
	mock.lockParse.Unlock()
	return mock.ParseFunc(commentlines)
}

// ParseCalls gets all the calls that were made to Parse.
// Check the length with:
//
//	len(mockedValueParser.ParseCalls())
func (mock *MockValueParser) ParseCalls() []struct {
	Commentlines []string
} {
	var calls []struct {
		Commentlines []string
	}
	mock.lockParse.RLock()
	calls = mock.calls.Parse
	mock.lockParse.RUnlock()
	return calls
}

// Ensure that MockOperationValidationBuilder does implement ifaces.OperationValidationBuilder.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.OperationValidationBuilder = &MockOperationValidationBuilder{}

// MockOperationValidationBuilder is a mock implementation of ifaces.OperationValidationBuilder.
//
//	func TestSomethingThatUsesOperationValidationBuilder(t *testing.T) {
//
//		// make and configure a mocked ifaces.OperationValidationBuilder
//		mockedOperationValidationBuilder := &MockOperationValidationBuilder{
//			SetCollectionFormatFunc: func(collectionFormat string)  {
//				panic("mock out the SetCollectionFormat method")
//			},
//			SetDefaultFunc: func(defaultValue any)  {
//				panic("mock out the SetDefault method")
//			},
//			SetEnumFunc: func(enumValue string)  {
//				panic("mock out the SetEnum method")
//			},
//			SetExampleFunc: func(example any)  {
//				panic("mock out the SetExample method")
//			},
//			SetMaxItemsFunc: func(maxItems int64)  {
//				panic("mock out the SetMaxItems method")
//			},
//			SetMaxLengthFunc: func(maxLength int64)  {
//				panic("mock out the SetMaxLength method")
//			},
//			SetMaximumFunc: func(maxium float64, isExclusive bool)  {
//				panic("mock out the SetMaximum method")
//			},
//			SetMinItemsFunc: func(minItems int64)  {
//				panic("mock out the SetMinItems method")
//			},
//			SetMinLengthFunc: func(minLength int64)  {
//				panic("mock out the SetMinLength method")
//			},
//			SetMinimumFunc: func(minimum float64, isExclusive bool)  {
//				panic("mock out the SetMinimum method")
//			},
//			SetMultipleOfFunc: func(multiple float64)  {
//				panic("mock out the SetMultipleOf method")
//			},
//			SetPatternFunc: func(pattern string)  {
//				panic("mock out the SetPattern method")
//			},
//			SetUniqueFunc: func(isUniqueItems bool)  {
//				panic("mock out the SetUnique method")
//			},
//		}
//
//		// use mockedOperationValidationBuilder in code that requires ifaces.OperationValidationBuilder
//		// and then make assertions.
//
//	}
type MockOperationValidationBuilder struct {
	// SetCollectionFormatFunc mocks the SetCollectionFormat method.
	SetCollectionFormatFunc func(collectionFormat string)

	// SetDefaultFunc mocks the SetDefault method.
	SetDefaultFunc func(defaultValue any)

	// SetEnumFunc mocks the SetEnum method.
	SetEnumFunc func(enumValue string)

	// SetExampleFunc mocks the SetExample method.
	SetExampleFunc func(example any)

	// SetMaxItemsFunc mocks the SetMaxItems method.
	SetMaxItemsFunc func(maxItems int64)

	// SetMaxLengthFunc mocks the SetMaxLength method.
	SetMaxLengthFunc func(maxLength int64)

	// SetMaximumFunc mocks the SetMaximum method.
	SetMaximumFunc func(maxium float64, isExclusive bool)

	// SetMinItemsFunc mocks the SetMinItems method.
	SetMinItemsFunc func(minItems int64)

	// SetMinLengthFunc mocks the SetMinLength method.
	SetMinLengthFunc func(minLength int64)

	// SetMinimumFunc mocks the SetMinimum method.
	SetMinimumFunc func(minimum float64, isExclusive bool)

	// SetMultipleOfFunc mocks the SetMultipleOf method.
	SetMultipleOfFunc func(multiple float64)

	// SetPatternFunc mocks the SetPattern method.
	SetPatternFunc func(pattern string)

	// SetUniqueFunc mocks the SetUnique method.
	SetUniqueFunc func(isUniqueItems bool)

	// calls tracks calls to the methods.
	calls struct {
		// SetCollectionFormat holds details about calls to the SetCollectionFormat method.
		SetCollectionFormat []struct {
			// CollectionFormat is the collectionFormat argument value.
			CollectionFormat string
		}
		// SetDefault holds details about calls to the SetDefault method.
		SetDefault []struct {
			// DefaultValue is the defaultValue argument value.
			DefaultValue any
		}
		// SetEnum holds details about calls to the SetEnum method.
		SetEnum []struct {
			// EnumValue is the enumValue argument value.
			EnumValue string
		}
		// SetExample holds details about calls to the SetExample method.
		SetExample []struct {
			// Example is the example argument value.
			Example any
		}
		// SetMaxItems holds details about calls to the SetMaxItems method.
		SetMaxItems []struct {
			// MaxItems is the maxItems argument value.
			MaxItems int64
		}
		// SetMaxLength holds details about calls to the SetMaxLength method.
		SetMaxLength []struct {
			// MaxLength is the maxLength argument value.
			MaxLength int64
		}
		// SetMaximum holds details about calls to the SetMaximum method.
		SetMaximum []struct {
			// Maxium is the maxium argument value.
			Maxium float64
			// IsExclusive is the isExclusive argument value.
			IsExclusive bool
		}
		// SetMinItems holds details about calls to the SetMinItems method.
		SetMinItems []struct {
			// MinItems is the minItems argument value.
			MinItems int64
		}
		// SetMinLength holds details about calls to the SetMinLength method.
		SetMinLength []struct {
			// MinLength is the minLength argument value.
			MinLength int64
		}
		// SetMinimum holds details about calls to the SetMinimum method.
		SetMinimum []struct {
			// Minimum is the minimum argument value.
			Minimum float64
			// IsExclusive is the isExclusive argument value.
			IsExclusive bool
		}
		// SetMultipleOf holds details about calls to the SetMultipleOf method.
		SetMultipleOf []struct {
			// Multiple is the multiple argument value.
			Multiple float64
		}
		// SetPattern holds details about calls to the SetPattern method.
		SetPattern []struct {
			// Pattern is the pattern argument value.
			Pattern string
		}
		// SetUnique holds details about calls to the SetUnique method.
		SetUnique []struct {
			// IsUniqueItems is the isUniqueItems argument value.
			IsUniqueItems bool
		}
	}
	lockSetCollectionFormat sync.RWMutex
	lockSetDefault          sync.RWMutex
	lockSetEnum             sync.RWMutex
	lockSetExample          sync.RWMutex
	lockSetMaxItems         sync.RWMutex
	lockSetMaxLength        sync.RWMutex
	lockSetMaximum          sync.RWMutex
	lockSetMinItems         sync.RWMutex
	lockSetMinLength        sync.RWMutex
	lockSetMinimum          sync.RWMutex
	lockSetMultipleOf       sync.RWMutex
	lockSetPattern          sync.RWMutex
	lockSetUnique           sync.RWMutex
}

// SetCollectionFormat calls SetCollectionFormatFunc.
func (mock *MockOperationValidationBuilder) SetCollectionFormat(collectionFormat string) {
	if mock.SetCollectionFormatFunc == nil {
		panic("MockOperationValidationBuilder.SetCollectionFormatFunc: method is nil but OperationValidationBuilder.SetCollectionFormat was just called")
	}
	callInfo := struct {
		CollectionFormat string
	}{
		CollectionFormat: collectionFormat,
	}
	mock.lockSetCollectionFormat.Lock()
	mock.calls.SetCollectionFormat = append(mock.calls.SetCollectionFormat, callInfo)
	mock.lockSetCollectionFormat.Unlock()
	mock.SetCollectionFormatFunc(collectionFormat)
}

// SetCollectionFormatCalls gets all the calls that were made to SetCollectionFormat.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetCollectionFormatCalls())
func (mock *MockOperationValidationBuilder) SetCollectionFormatCalls() []struct {
	CollectionFormat string
} {
	var calls []struct {
		CollectionFormat string
	}
	mock.lockSetCollectionFormat.RLock()
	calls = mock.calls.SetCollectionFormat
	mock.lockSetCollectionFormat.RUnlock()
	return calls
}

// SetDefault calls SetDefaultFunc.
func (mock *MockOperationValidationBuilder) SetDefault(defaultValue any) {
	if mock.SetDefaultFunc == nil {
		panic("MockOperationValidationBuilder.SetDefaultFunc: method is nil but OperationValidationBuilder.SetDefault was just called")
	}
	callInfo := struct {
		DefaultValue any
	}{
		DefaultValue: defaultValue,
	}
	mock.lockSetDefault.Lock()
	mock.calls.SetDefault = append(mock.calls.SetDefault, callInfo)
	mock.lockSetDefault.Unlock()
	mock.SetDefaultFunc(defaultValue)
}

// SetDefaultCalls gets all the calls that were made to SetDefault.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetDefaultCalls())
func (mock *MockOperationValidationBuilder) SetDefaultCalls() []struct {
	DefaultValue any
} {
	var calls []struct {
		DefaultValue any
	}
	mock.lockSetDefault.RLock()
	calls = mock.calls.SetDefault
	mock.lockSetDefault.RUnlock()
	return calls
}

// SetEnum calls SetEnumFunc.
func (mock *MockOperationValidationBuilder) SetEnum(enumValue string) {
	if mock.SetEnumFunc == nil {
		panic("MockOperationValidationBuilder.SetEnumFunc: method is nil but OperationValidationBuilder.SetEnum was just called")
	}
	callInfo := struct {
		EnumValue string
	}{
		EnumValue: enumValue,
	}
	mock.lockSetEnum.Lock()
	mock.calls.SetEnum = append(mock.calls.SetEnum, callInfo)
	mock.lockSetEnum.Unlock()
	mock.SetEnumFunc(enumValue)
}

// SetEnumCalls gets all the calls that were made to SetEnum.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetEnumCalls())
func (mock *MockOperationValidationBuilder) SetEnumCalls() []struct {
	EnumValue string
} {
	var calls []struct {
		EnumValue string
	}
	mock.lockSetEnum.RLock()
	calls = mock.calls.SetEnum
	mock.lockSetEnum.RUnlock()
	return calls
}

// SetExample calls SetExampleFunc.
func (mock *MockOperationValidationBuilder) SetExample(example any) {
	if mock.SetExampleFunc == nil {
		panic("MockOperationValidationBuilder.SetExampleFunc: method is nil but OperationValidationBuilder.SetExample was just called")
	}
	callInfo := struct {
		Example any
	}{
		Example: example,
	}
	mock.lockSetExample.Lock()
	mock.calls.SetExample = append(mock.calls.SetExample, callInfo)
	mock.lockSetExample.Unlock()
	mock.SetExampleFunc(example)
}

// SetExampleCalls gets all the calls that were made to SetExample.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetExampleCalls())
func (mock *MockOperationValidationBuilder) SetExampleCalls() []struct {
	Example any
} {
	var calls []struct {
		Example any
	}
	mock.lockSetExample.RLock()
	calls = mock.calls.SetExample
	mock.lockSetExample.RUnlock()
	return calls
}

// SetMaxItems calls SetMaxItemsFunc.
func (mock *MockOperationValidationBuilder) SetMaxItems(maxItems int64) {
	if mock.SetMaxItemsFunc == nil {
		panic("MockOperationValidationBuilder.SetMaxItemsFunc: method is nil but OperationValidationBuilder.SetMaxItems was just called")
	}
	callInfo := struct {
		MaxItems int64
	}{
		MaxItems: maxItems,
	}
	mock.lockSetMaxItems.Lock()
	mock.calls.SetMaxItems = append(mock.calls.SetMaxItems, callInfo)
	mock.lockSetMaxItems.Unlock()
	mock.SetMaxItemsFunc(maxItems)
}

// SetMaxItemsCalls gets all the calls that were made to SetMaxItems.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetMaxItemsCalls())
func (mock *MockOperationValidationBuilder) SetMaxItemsCalls() []struct {
	MaxItems int64
} {
	var calls []struct {
		MaxItems int64
	}
	mock.lockSetMaxItems.RLock()
	calls = mock.calls.SetMaxItems
	mock.lockSetMaxItems.RUnlock()
	return calls
}

// SetMaxLength calls SetMaxLengthFunc.
func (mock *MockOperationValidationBuilder) SetMaxLength(maxLength int64) {
	if mock.SetMaxLengthFunc == nil {
		panic("MockOperationValidationBuilder.SetMaxLengthFunc: method is nil but OperationValidationBuilder.SetMaxLength was just called")
	}
	callInfo := struct {
		MaxLength int64
	}{
		MaxLength: maxLength,
	}
	mock.lockSetMaxLength.Lock()
	mock.calls.SetMaxLength = append(mock.calls.SetMaxLength, callInfo)
	mock.lockSetMaxLength.Unlock()
	mock.SetMaxLengthFunc(maxLength)
}

// SetMaxLengthCalls gets all the calls that were made to SetMaxLength.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetMaxLengthCalls())
func (mock *MockOperationValidationBuilder) SetMaxLengthCalls() []struct {
	MaxLength int64
} {
	var calls []struct {
		MaxLength int64
	}
	mock.lockSetMaxLength.RLock()
	calls = mock.calls.SetMaxLength
	mock.lockSetMaxLength.RUnlock()
	return calls
}

// SetMaximum calls SetMaximumFunc.
func (mock *MockOperationValidationBuilder) SetMaximum(maxium float64, isExclusive bool) {
	if mock.SetMaximumFunc == nil {
		panic("MockOperationValidationBuilder.SetMaximumFunc: method is nil but OperationValidationBuilder.SetMaximum was just called")
	}
	callInfo := struct {
		Maxium      float64
		IsExclusive bool
	}{
		Maxium:      maxium,
		IsExclusive: isExclusive,
	}
	mock.lockSetMaximum.Lock()
	mock.calls.SetMaximum = append(mock.calls.SetMaximum, callInfo)
	mock.lockSetMaximum.Unlock()
	mock.SetMaximumFunc(maxium, isExclusive)
}

// SetMaximumCalls gets all the calls that were made to SetMaximum.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetMaximumCalls())
func (mock *MockOperationValidationBuilder) SetMaximumCalls() []struct {
	Maxium      float64
	IsExclusive bool
} {
	var calls []struct {
		Maxium      float64
		IsExclusive bool
	}
	mock.lockSetMaximum.RLock()
	calls = mock.calls.SetMaximum
	mock.lockSetMaximum.RUnlock()
	return calls
}

// SetMinItems calls SetMinItemsFunc.
func (mock *MockOperationValidationBuilder) SetMinItems(minItems int64) {
	if mock.SetMinItemsFunc == nil {
		panic("MockOperationValidationBuilder.SetMinItemsFunc: method is nil but OperationValidationBuilder.SetMinItems was just called")
	}
	callInfo := struct {
		MinItems int64
	}{
		MinItems: minItems,
	}
	mock.lockSetMinItems.Lock()
	mock.calls.SetMinItems = append(mock.calls.SetMinItems, callInfo)
	mock.lockSetMinItems.Unlock()
	mock.SetMinItemsFunc(minItems)
}

// SetMinItemsCalls gets all the calls that were made to SetMinItems.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetMinItemsCalls())
func (mock *MockOperationValidationBuilder) SetMinItemsCalls() []struct {
	MinItems int64
} {
	var calls []struct {
		MinItems int64
	}
	mock.lockSetMinItems.RLock()
	calls = mock.calls.SetMinItems
	mock.lockSetMinItems.RUnlock()
	return calls
}

// SetMinLength calls SetMinLengthFunc.
func (mock *MockOperationValidationBuilder) SetMinLength(minLength int64) {
	if mock.SetMinLengthFunc == nil {
		panic("MockOperationValidationBuilder.SetMinLengthFunc: method is nil but OperationValidationBuilder.SetMinLength was just called")
	}
	callInfo := struct {
		MinLength int64
	}{
		MinLength: minLength,
	}
	mock.lockSetMinLength.Lock()
	mock.calls.SetMinLength = append(mock.calls.SetMinLength, callInfo)
	mock.lockSetMinLength.Unlock()
	mock.SetMinLengthFunc(minLength)
}

// SetMinLengthCalls gets all the calls that were made to SetMinLength.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetMinLengthCalls())
func (mock *MockOperationValidationBuilder) SetMinLengthCalls() []struct {
	MinLength int64
} {
	var calls []struct {
		MinLength int64
	}
	mock.lockSetMinLength.RLock()
	calls = mock.calls.SetMinLength
	mock.lockSetMinLength.RUnlock()
	return calls
}

// SetMinimum calls SetMinimumFunc.
func (mock *MockOperationValidationBuilder) SetMinimum(minimum float64, isExclusive bool) {
	if mock.SetMinimumFunc == nil {
		panic("MockOperationValidationBuilder.SetMinimumFunc: method is nil but OperationValidationBuilder.SetMinimum was just called")
	}
	callInfo := struct {
		Minimum     float64
		IsExclusive bool
	}{
		Minimum:     minimum,
		IsExclusive: isExclusive,
	}
	mock.lockSetMinimum.Lock()
	mock.calls.SetMinimum = append(mock.calls.SetMinimum, callInfo)
	mock.lockSetMinimum.Unlock()
	mock.SetMinimumFunc(minimum, isExclusive)
}

// SetMinimumCalls gets all the calls that were made to SetMinimum.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetMinimumCalls())
func (mock *MockOperationValidationBuilder) SetMinimumCalls() []struct {
	Minimum     float64
	IsExclusive bool
} {
	var calls []struct {
		Minimum     float64
		IsExclusive bool
	}
	mock.lockSetMinimum.RLock()
	calls = mock.calls.SetMinimum
	mock.lockSetMinimum.RUnlock()
	return calls
}

// SetMultipleOf calls SetMultipleOfFunc.
func (mock *MockOperationValidationBuilder) SetMultipleOf(multiple float64) {
	if mock.SetMultipleOfFunc == nil {
		panic("MockOperationValidationBuilder.SetMultipleOfFunc: method is nil but OperationValidationBuilder.SetMultipleOf was just called")
	}
	callInfo := struct {
		Multiple float64
	}{
		Multiple: multiple,
	}
	mock.lockSetMultipleOf.Lock()
	mock.calls.SetMultipleOf = append(mock.calls.SetMultipleOf, callInfo)
	mock.lockSetMultipleOf.Unlock()
	mock.SetMultipleOfFunc(multiple)
}

// SetMultipleOfCalls gets all the calls that were made to SetMultipleOf.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetMultipleOfCalls())
func (mock *MockOperationValidationBuilder) SetMultipleOfCalls() []struct {
	Multiple float64
} {
	var calls []struct {
		Multiple float64
	}
	mock.lockSetMultipleOf.RLock()
	calls = mock.calls.SetMultipleOf
	mock.lockSetMultipleOf.RUnlock()
	return calls
}

// SetPattern calls SetPatternFunc.
func (mock *MockOperationValidationBuilder) SetPattern(pattern string) {
	if mock.SetPatternFunc == nil {
		panic("MockOperationValidationBuilder.SetPatternFunc: method is nil but OperationValidationBuilder.SetPattern was just called")
	}
	callInfo := struct {
		Pattern string
	}{
		Pattern: pattern,
	}
	mock.lockSetPattern.Lock()
	mock.calls.SetPattern = append(mock.calls.SetPattern, callInfo)
	mock.lockSetPattern.Unlock()
	mock.SetPatternFunc(pattern)
}

// SetPatternCalls gets all the calls that were made to SetPattern.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetPatternCalls())
func (mock *MockOperationValidationBuilder) SetPatternCalls() []struct {
	Pattern string
} {
	var calls []struct {
		Pattern string
	}
	mock.lockSetPattern.RLock()
	calls = mock.calls.SetPattern
	mock.lockSetPattern.RUnlock()
	return calls
}

// SetUnique calls SetUniqueFunc.
func (mock *MockOperationValidationBuilder) SetUnique(isUniqueItems bool) {
	if mock.SetUniqueFunc == nil {
		panic("MockOperationValidationBuilder.SetUniqueFunc: method is nil but OperationValidationBuilder.SetUnique was just called")
	}
	callInfo := struct {
		IsUniqueItems bool
	}{
		IsUniqueItems: isUniqueItems,
	}
	mock.lockSetUnique.Lock()
	mock.calls.SetUnique = append(mock.calls.SetUnique, callInfo)
	mock.lockSetUnique.Unlock()
	mock.SetUniqueFunc(isUniqueItems)
}

// SetUniqueCalls gets all the calls that were made to SetUnique.
// Check the length with:
//
//	len(mockedOperationValidationBuilder.SetUniqueCalls())
func (mock *MockOperationValidationBuilder) SetUniqueCalls() []struct {
	IsUniqueItems bool
} {
	var calls []struct {
		IsUniqueItems bool
	}
	mock.lockSetUnique.RLock()
	calls = mock.calls.SetUnique
	mock.lockSetUnique.RUnlock()
	return calls
}

// Ensure that MockObjecter does implement ifaces.Objecter.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.Objecter = &MockObjecter{}

// MockObjecter is a mock implementation of ifaces.Objecter.
//
//	func TestSomethingThatUsesObjecter(t *testing.T) {
//
//		// make and configure a mocked ifaces.Objecter
//		mockedObjecter := &MockObjecter{
//			ObjFunc: func() *types.TypeName {
//				panic("mock out the Obj method")
//			},
//		}
//
//		// use mockedObjecter in code that requires ifaces.Objecter
//		// and then make assertions.
//
//	}
type MockObjecter struct {
	// ObjFunc mocks the Obj method.
	ObjFunc func() *types.TypeName

	// calls tracks calls to the methods.
	calls struct {
		// Obj holds details about calls to the Obj method.
		Obj []struct {
		}
	}
	lockObj sync.RWMutex
}

// Obj calls ObjFunc.
func (mock *MockObjecter) Obj() *types.TypeName {
	if mock.ObjFunc == nil {
		panic("MockObjecter.ObjFunc: method is nil but Objecter.Obj was just called")
	}
	callInfo := struct {
	}{}
	mock.lockObj.Lock()
	mock.calls.Obj = append(mock.calls.Obj, callInfo)
	mock.lockObj.Unlock()
	return mock.ObjFunc()
}

// ObjCalls gets all the calls that were made to Obj.
// Check the length with:
//
//	len(mockedObjecter.ObjCalls())
func (mock *MockObjecter) ObjCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockObj.RLock()
	calls = mock.calls.Obj
	mock.lockObj.RUnlock()
	return calls
}
