// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// The ledger is the committed half of this tool.
//
// The corpus itself is not copied here — it belongs to the Go distribution and is read where it lies
// — so without a record there would be nothing to review and nothing to notice when Go moves. A run
// against a newer Go shows up as a diff of this file: a script that changed families, a skip reason
// that no longer applies, a tree that started disagreeing.

func writeLedgerFile(goRoot string, outcomes []outcome) error {
	var b strings.Builder

	b.WriteString("# go command corpus — ledger\n\n")
	b.WriteString("Generated by `go run ./hack/go-loader -go <checkout> corpus -write-ledger`.\n")
	b.WriteString("Do not edit by hand; re-run against a newer Go and review the diff.\n\n")
	fmt.Fprintf(&b, "Go checkout: `%s`\n\n", goVersion(goRoot))

	counts := map[string]int{}
	for _, o := range outcomes {
		counts[o.status]++
	}
	fmt.Fprintf(&b,
		"| scripts | agree | differ | go-rejects | skip | error |\n|---|---|---|---|---|---|\n| %d | %d | %d | %d | %d | %d |\n\n",
		len(outcomes), counts["agree"], counts["differ"], counts["go-rejects"], counts["skip"], counts["error"])

	section := func(title, status string) {
		var rows []string
		for _, o := range outcomes {
			if o.status != status {
				continue
			}
			rows = append(rows, fmt.Sprintf("| `%s` | %s |", o.script, o.detail))
		}
		if len(rows) == 0 {
			return
		}
		fmt.Fprintf(&b, "## %s (%d)\n\n| script | detail |\n|---|---|\n%s\n\n",
			title, len(rows), strings.Join(rows, "\n"))
	}

	// Differences first: they are the reason to run this at all.
	section("Differ", "differ")
	section("Error", "error")
	section("Go rejects the tree, we read it", "go-rejects")
	section("Agree", "agree")
	section("Skipped", "skip")

	return os.WriteFile("hack/go-loader/ledger.md", []byte(b.String()), filePerm)
}

// goVersion identifies the checkout the corpus came from, so a ledger diff says which Go moved.
func goVersion(goRoot string) string {
	out, err := exec.CommandContext(context.Background(), "git", "-C", goRoot, "describe", "--tags").Output()
	if err != nil {
		return "unknown"
	}

	return strings.TrimSpace(string(out))
}
