// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

//go:generate go run ./gen -out ../../../docs/annotation-keywords.md

package grammar

// keywords is the authoritative table of `keyword: value` forms the
// parser recognizes at v1 parity.
//
// OAI 3.x additions and any workshop outcomes (W2 enum, W3 example)
// land as new entries here — no parser change required.
//
// The docs generator (gen/main.go) consumes this slice to emit
// docs/annotation-keywords.md; see P0.4.
//
// Authored canonical table, not mutable state; lives at package level so
// it compiles into the parser binary without per-call allocation. Exposed
// via Lookup / Keywords accessors.
//
//nolint:gochecknoglobals // see godoc above
var keywords = []Keyword{
	// --- numeric validations ---

	keyword("maximum",
		aka("max"),
		asNumber(),
		inParam("Maximum value of the parameter (inclusive by default)."),
		inHeader("Maximum value of the header (inclusive by default)."),
		inSchema("Maximum value of the property (inclusive by default)."),
		inItems("Maximum value of each array item (inclusive by default)."),
	),
	keyword("minimum",
		aka("min"),
		asNumber(),
		inParam("Minimum value of the parameter (inclusive by default)."),
		inHeader("Minimum value of the header (inclusive by default)."),
		inSchema("Minimum value of the property (inclusive by default)."),
		inItems("Minimum value of each array item (inclusive by default)."),
	),
	keyword("multipleOf",
		aka("multiple of", "multiple-of"),
		asNumber(),
		inParam("Parameter value must be a multiple of this number."),
		inHeader("Header value must be a multiple of this number."),
		inSchema("Property value must be a multiple of this number."),
		inItems("Each array item must be a multiple of this number."),
	),

	// --- string-length validations ---

	keyword("maxLength",
		aka("max length", "max-length", "maxLen", "max len", "max-len"),
		asInteger(),
		inParam("Maximum length of the string parameter."),
		inHeader("Maximum length of the header."),
		inSchema("Maximum length of the string property."),
		inItems("Maximum length of each string item."),
	),
	keyword("minLength",
		aka("min length", "min-length", "minLen", "min len", "min-len"),
		asInteger(),
		inParam("Minimum length of the string parameter."),
		inHeader("Minimum length of the header."),
		inSchema("Minimum length of the string property."),
		inItems("Minimum length of each string item."),
	),
	keyword("pattern",
		asString(),
		inParam("Regular expression the parameter must match."),
		inHeader("Regular expression the header must match."),
		inSchema("Regular expression the property must match."),
		inItems("Regular expression each array item must match."),
	),

	// --- array validations ---

	keyword("maxItems",
		aka("max items", "max-items", "max.items"),
		asInteger(),
		inParam("Maximum number of items in the parameter array."),
		inHeader("Maximum number of items in the header array."),
		inSchema("Maximum number of items in the array property."),
		inItems("Maximum number of items at this nesting level."),
	),
	keyword("minItems",
		aka("min items", "min-items", "min.items"),
		asInteger(),
		inParam("Minimum number of items in the parameter array."),
		inHeader("Minimum number of items in the header array."),
		inSchema("Minimum number of items in the array property."),
		inItems("Minimum number of items at this nesting level."),
	),
	keyword("unique",
		asBoolean(),
		inParam("Whether items in the parameter array must be unique."),
		inHeader("Whether items in the header array must be unique."),
		inSchema("Whether items in the array property must be unique."),
		inItems("Whether items at this level must be unique."),
	),
	keyword("collectionFormat",
		aka("collection format", "collection-format"),
		asStringEnum("csv", "ssv", "tsv", "pipes", "multi"),
		inParam("Array serialization format (csv, ssv, tsv, pipes, multi)."),
		inHeader("Array serialization in the header (csv, ssv, tsv, pipes)."),
		inItems("Nested-array serialization format."),
	),

	// --- value-bearing keywords (field-type-dependent) ---

	keyword("enum",
		asCommaList(),
		inParam("Allowed values for the parameter (comma-separated)."),
		inHeader("Allowed values for the header (comma-separated)."),
		inSchema("Allowed values for the property (comma-separated)."),
		inItems("Allowed values for each array item (comma-separated)."),
	),
	keyword("default",
		asRawValue(),
		inParam("Default value when the parameter is omitted."),
		inHeader("Default value when the header is absent."),
		inSchema("Default value when the property is absent."),
		inItems("Default value for each array item."),
	),
	keyword("example",
		asRawValue(),
		inParam("Example value for documentation."),
		inHeader("Example value for documentation."),
		inSchema("Example value for documentation."),
		inItems("Example value for documentation."),
	),

	// --- property flags ---

	keyword("required",
		asBoolean(),
		inParam("Whether the parameter is required."),
		inSchema("Whether the property is required."),
	),
	keyword("readOnly",
		aka("read only", "read-only"),
		asBoolean(),
		inSchema("Whether the property is read-only (server-set; clients may not write it)."),
	),
	keyword("discriminator",
		asBoolean(),
		inSchema("Marks this property as the polymorphic-schema discriminator."),
	),
	keyword("deprecated",
		asBoolean(),
		inOperation("Marks this operation as deprecated."),
		inRoute("Marks this route as deprecated."),
		inSchema("Marks this property as deprecated."),
	),

	// --- parameter-location directive ---

	keyword("in",
		asStringEnum("query", "path", "header", "body", "formData"),
		inParam("Parameter location: query, path, header, body, or formData."),
	),

	// --- meta single-line keywords ---

	keyword("schemes",
		asCommaList(),
		inMeta("API schemes (http, https, ws, wss)."),
		inRoute("Route-level schemes override."),
		inOperation("Operation-level schemes override."),
	),
	keyword("version",
		asString(),
		inMeta("API version string."),
	),
	keyword("host",
		asString(),
		inMeta("Host (and optional port) serving the API."),
	),
	keyword("basePath",
		aka("base path", "base-path"),
		asString(),
		inMeta("URL prefix for all API paths."),
	),
	keyword("license",
		asString(),
		inMeta("License information (name, optional URL)."),
	),
	keyword("contact",
		aka("contact info", "contact-info"),
		asString(),
		inMeta("Contact information (name, email, URL)."),
	),

	// --- block-header keywords (multi-line bodies) ---

	keyword("consumes",
		asRawBlock(),
		inMeta("Default MIME types the API consumes."),
		inRoute("MIME types this route consumes."),
		inOperation("MIME types this operation consumes."),
	),
	keyword("produces",
		asRawBlock(),
		inMeta("Default MIME types the API produces."),
		inRoute("MIME types this route produces."),
		inOperation("MIME types this operation produces."),
	),
	keyword("security",
		asRawBlock(),
		inMeta("Default security requirements for the API."),
		inRoute("Security requirements for this route."),
		inOperation("Security requirements for this operation."),
	),
	keyword("securityDefinitions",
		aka("security definitions", "security-definitions"),
		asRawBlock(),
		inMeta("Declared security schemes (apiKey, basic, oauth2)."),
	),
	keyword("responses",
		asRawBlock(),
		inRoute("Response mapping: status → response name."),
		inOperation("Response mapping: status → response name."),
	),
	keyword("parameters",
		asRawBlock(),
		inRoute("Parameter declarations for this route."),
		inOperation("Parameter declarations for this operation."),
	),
	keyword("extensions",
		asRawBlock(),
		inMeta("Custom x-* vendor extensions at the spec level."),
		inRoute("Custom x-* vendor extensions on this route."),
		inOperation("Custom x-* vendor extensions on this operation."),
		inSchema("Custom x-* vendor extensions on this schema."),
	),
	keyword("infoExtensions",
		aka("info extensions", "info-extensions"),
		asRawBlock(),
		inMeta("Custom x-* vendor extensions on the info block."),
	),
	keyword("tos",
		aka("terms of service", "terms-of-service", "termsOfService"),
		asRawBlock(),
		inMeta("Terms-of-service URL or text."),
	),

	// --- W5 opportunistic: externalDocs ---

	keyword("externalDocs",
		aka("external docs", "external-docs"),
		asRawBlock(),
		inMeta("External documentation reference."),
		inRoute("External documentation reference."),
		inOperation("External documentation reference."),
		inSchema("External documentation reference."),
	),
}
