name: Release on tag

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+*

jobs:
  gh-release:
    name: Create release
    permissions:
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/release.yml@69ea5ee4c72ab9ceb97db3dabbe2c0f0a148ef8a # v0.6.0
    with:
      tag: ${{ github.ref_name }}
      is-monorepo: 'true'
    secrets: inherit
